name: Update README

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "**/README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up timezone
        run: |
          # GitHub Actions 환경에서 한국 시간대 설정
          sudo timedatectl set-timezone Asia/Seoul
          echo "Current timezone: $(timedatectl show --property=Timezone --value)"
          echo "Current time: $(date)"

      - name: Install dependencies
        run: |
          pip install PyYAML
          # Ubuntu에서 timezone 데이터 업데이트 (zoneinfo 사용을 위해)
          sudo apt-get update && sudo apt-get install -y tzdata

      - name: Update personal README
        run: |
          echo "🔍 GitHub Actions 환경 정보:"
          echo "시간대: $(timedatectl show --property=Timezone --value)"
          echo "현재 시간: $(date)"
          echo "Git 설정 확인:"
          git config --list | grep -E "(user|core)" || true
          echo "🚀 README 업데이트 실행:"
          python .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update README files [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
