name: Update README

on:
  push:
    branches: [main]
    paths:
      - "*/*/**" # 사용자 폴더 내 모든 파일
  workflow_dispatch: # 수동 실행 가능

# 동시 실행 방지
concurrency:
  group: update-readme-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'Auto-update README') }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up timezone
        run: |
          # GitHub Actions 환경에서 한국 시간대 설정
          sudo timedatectl set-timezone Asia/Seoul
          echo "Current timezone: $(timedatectl show --property=Timezone --value)"
          echo "Current time: $(date)"

      - name: Install dependencies
        run: |
          pip install PyYAML
          # Ubuntu에서 timezone 데이터 업데이트 (zoneinfo 사용을 위해)
          sudo apt-get update && sudo apt-get install -y tzdata

      - name: Update personal README
        run: |
          python .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 원격 브랜치와 동기화
          git fetch origin ${{ github.ref_name }}
          
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # 변경사항이 있다면 rebase 후 푸시
            if ! git diff --quiet HEAD origin/${{ github.ref_name }}; then
              echo "Remote has changes, rebasing..."
              git pull --rebase origin ${{ github.ref_name }} || {
                echo "Rebase failed, trying merge strategy"
                git rebase --abort
                git pull origin ${{ github.ref_name }}
              }
            fi
            
            git commit -m "Auto-update README files [skip ci]" || echo "Nothing to commit"
            git push origin HEAD:${{ github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
